### ISSUE TITLE
ImportError: cannot import name 'API'

### ISSUE THREAD

**Issue by ErikHendriks** [hootnot/oanda-api-v20#150]
For a year now i run oandapyV20 without problems. After a fresh ubuntu install I have problems with a import error, at first i thought it was a pip issue but i purged pip and try to install without pip, reinstalled pip and even an fresh install, again.
In the traceback it shows that oandapyV20 is imported,  but at "from oandapyV20 import API" i get this error "ImportError: cannot import name 'API'"

Thank you in advance

> Traceback (most recent call last):
  File "../../ethet13/calendar.py", line 2, in <module>
    import oandapyV20
  File "/home/ethet13/.local/lib/python3.6/site-packages/oandapyV20/__init__.py", line 2, in <module>
    from .oandapyV20 import API
  File "/home/ethet13/.local/lib/python3.6/site-packages/oandapyV20/oandapyV20.py", line 5, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python3/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.6/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.6/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.6/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/ethet13/calendar.py", line 7, in <module>
    from oandapyV20 import API
ImportError: cannot import name 'API'

**Comment by hootnot** [comment]
do you run it in a directory holding a directory called oandapyV20 for your own stuf ?

**Comment by ErikHendriks** [comment]
No from my home directory
Running it within the interpreter works, also with my other installation. However my scripts still getting the same error on both installations.

> Traceback (most recent call last):
  File "../../ethet13/calendar.py", line 2, in <module>
    import oandapyV20
  File "/home/ethet13/.local/lib/python3.6/site-packages/oandapyV20/__init__.py", line 2, in <module>
    from .oandapyV20 import API
  File "/home/ethet13/.local/lib/python3.6/site-packages/oandapyV20/oandapyV20.py", line 5, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3/dist-packages/urllib3/exceptions.py", line 2, in <module>
    from six.moves.http_client import (
  File "/usr/lib/python3/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python3/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python3/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/usr/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/usr/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/usr/lib/python3.6/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/usr/lib/python3.6/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.6/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/home/ethet13/calendar.py", line 7, in <module>
    from oandapyV20 import API
ImportError: cannot import name 'API'

**Comment by ErikHendriks** [comment]
Apparently it was my file naming 'calendar.py' after removing the file other files in the same directory worked again. I noticed running other scripts it was still complaining about calendar.py. urllib3 also imports a module calendar..

Thanks !

**Comment by hootnot** [comment]
... then I close this issue
